image: alpine/edge
secrets:
- e73c455a-0ae2-4d84-a748-a1962d4f2e84
- f996ca4e-955b-4473-b876-92ffa3cc560b
sources:
- git+ssh://git@git.sr.ht/~thepuzzlemaker/KerbalToolkit
tasks:
- mirror: |
    eval $(ssh-agent)
    ssh-add .ssh/f996ca4e-955b-4473-b876-92ffa3cc560b
    cd KerbalToolkit
    git remote add github git@github.com:ThePuzzlemaker/KerbalToolkit.git
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    git push --all --force github
