[package]
name = "kerbtk"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "MIT OR Apache-2.0"

[dependencies]
base64 = "0.22.0"
color-eyre = "0.6.3"
itertools = "0.12.1"
libm = "0.2.8"
nalgebra = { version = "0.32.6", default-features = false, features = ["serde", "serde-serialize", "std"] }
ordered-float = { version = "4.2.0", features = ["serde"] }
prost = "0.12.4"
prost-types = "0.12.4"
serde = { version = "1.0.197", features = ["derive"] }
time = { version = "0.3.34", features = ["default", "formatting", "serde", "parsing"] }
argmin = { version = "0.10.0", features = ["rayon"] }
argmin-math = { version = "0.4.0", features = ["vec"] }
rand = "0.8.5"

tungstenite = "0.21.0"
varint-rs = "2.2.0"
tracing = "0.1.40"

# kerbtk dependencies
eframe = { version = "0.27.2", optional = true }
egui = { version = "0.27.2", optional = true }
egui_extras = { version = "0.27.2", optional = true }
egui_grid = { path = "egui-grid", optional = true }
egui-notify = { version = "0.14.0", optional = true }
toml = { version = "0.8.12", optional = true }
tracing-subscriber = { version = "0.3.18", optional = true, features = ["env-filter"] }
egui-modal = { version = "0.3.6", optional = true }
fluent = { version = "0.16.1", optional = true }
fluent-templates = { version = "0.9.4", optional = true }
unic-langid = { version = "0.9.5", optional = true }
ron = { version = "0.8.1", optional = true }
rfd = { version = "0.14.1", optional = true }
parking_lot = { version = "0.12.2", optional = true, features = ["serde"] }
num_enum = { version = "0.7.2", optional = true }
nom = { version = "7.1.3", optional = true }
egui_plot = { version = "0.27.2", optional = true }
egui_form = { version = "0.1.1", features = ["validator_garde"] }
garde = "0.18.0"
argmin-observer-slog = "0.1.0"

[build-dependencies]
prost-build = { version = "0.12.4" }

[workspace]
members = [".", "egui-grid"]

[features]
default = []
kerbtk-bin = [
    "dep:eframe",
    "dep:egui",
    "dep:egui_extras",
    "dep:egui_grid",
    "dep:egui-notify",
    "dep:toml",
    "dep:tracing-subscriber",
    "dep:egui-modal",
    "dep:fluent",
    "dep:fluent-templates",
    "dep:unic-langid",
    "dep:ron",
    "dep:rfd",
    "dep:parking_lot",
    "dep:num_enum",
    "dep:nom",
    "dep:egui_plot"
]

[[bin]]
path = "src/bin/kerbtk.rs"
name = "kerbtk"
required-features = ["kerbtk-bin"]
