# Autogenerated using ProtoBuf.jl v1.0.16 on 2024-11-14T22:26:22.878
# Manually edited to fix some minor issues (e.g., JuliaFormatter bugs)
# original file: /home/wren/Code/Rust/KerbalToolkit/new/KerbTk/src/KRPC/krpc.proto (proto3 syntax)

using ProtoBuf: ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Tuple, Error
export Status, List, Argument, KRPCSet
export Exception, DictionaryEntry, ProcedureResult
export ConnectionResponse, Event, ConnectionRequest, ProcedureCall, Dictionary
export Response, Request

struct Tuple
    items::Vector{Vector{UInt8}}
end
PB.default_values(::Type{Tuple}) = (; items=Vector{Vector{UInt8}}())
PB.field_numbers(::Type{Tuple}) = (; items=1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Tuple})
    items = PB.BufferedVector{Vector{UInt8}}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, items)
        else
            Base.skip(d, wire_type)
        end
    end
    return Tuple(items[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Tuple)
    initpos = position(e.io)
    !isempty(x.items) && PB.encode(e, 1, x.items)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Tuple)
    encoded_size = 0
    !isempty(x.items) && (encoded_size += PB._encoded_size(x.items, 1))
    return encoded_size
end

struct Error
    service::String
    name::String
    description::String
    stack_trace::String
end
PB.default_values(::Type{Error}) = (; service="", name="", description="", stack_trace="")
PB.field_numbers(::Type{Error}) = (; service=1, name=2, description=3, stack_trace=4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Error})
    service = ""
    name = ""
    description = ""
    stack_trace = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            service = PB.decode(d, String)
        elseif field_number == 2
            name = PB.decode(d, String)
        elseif field_number == 3
            description = PB.decode(d, String)
        elseif field_number == 4
            stack_trace = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return Error(service, name, description, stack_trace)
end

struct Status
    version::String
    bytes_read::UInt64
    bytes_written::UInt64
    bytes_read_rate::Float32
    bytes_written_rate::Float32
    rpcs_executed::UInt64
    rpc_rate::Float32
    one_rpc_per_update::Bool
    max_time_per_update::UInt32
    adaptive_rate_control::Bool
    blocking_recv::Bool
    recv_timeout::UInt32
    time_per_rpc_update::Float32
    poll_time_per_rpc_update::Float32
    exec_time_per_rpc_update::Float32
    stream_rpcs::UInt32
    stream_rpcs_executed::UInt64
    stream_rpc_rate::Float32
    time_per_stream_update::Float32
end
function PB.default_values(::Type{Status})
    return (;
        version="",
        bytes_read=zero(UInt64),
        bytes_written=zero(UInt64),
        bytes_read_rate=zero(Float32),
        bytes_written_rate=zero(Float32),
        rpcs_executed=zero(UInt64),
        rpc_rate=zero(Float32),
        one_rpc_per_update=false,
        max_time_per_update=zero(UInt32),
        adaptive_rate_control=false,
        blocking_recv=false,
        recv_timeout=zero(UInt32),
        time_per_rpc_update=zero(Float32),
        poll_time_per_rpc_update=zero(Float32),
        exec_time_per_rpc_update=zero(Float32),
        stream_rpcs=zero(UInt32),
        stream_rpcs_executed=zero(UInt64),
        stream_rpc_rate=zero(Float32),
        time_per_stream_update=zero(Float32),
    )
end
function PB.field_numbers(::Type{Status})
    return (;
        version=1,
        bytes_read=2,
        bytes_written=3,
        bytes_read_rate=4,
        bytes_written_rate=5,
        rpcs_executed=6,
        rpc_rate=7,
        one_rpc_per_update=8,
        max_time_per_update=9,
        adaptive_rate_control=10,
        blocking_recv=11,
        recv_timeout=12,
        time_per_rpc_update=13,
        poll_time_per_rpc_update=14,
        exec_time_per_rpc_update=15,
        stream_rpcs=16,
        stream_rpcs_executed=17,
        stream_rpc_rate=18,
        time_per_stream_update=19,
    )
end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Status})
    version = ""
    bytes_read = zero(UInt64)
    bytes_written = zero(UInt64)
    bytes_read_rate = zero(Float32)
    bytes_written_rate = zero(Float32)
    rpcs_executed = zero(UInt64)
    rpc_rate = zero(Float32)
    one_rpc_per_update = false
    max_time_per_update = zero(UInt32)
    adaptive_rate_control = false
    blocking_recv = false
    recv_timeout = zero(UInt32)
    time_per_rpc_update = zero(Float32)
    poll_time_per_rpc_update = zero(Float32)
    exec_time_per_rpc_update = zero(Float32)
    stream_rpcs = zero(UInt32)
    stream_rpcs_executed = zero(UInt64)
    stream_rpc_rate = zero(Float32)
    time_per_stream_update = zero(Float32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            version = PB.decode(d, String)
        elseif field_number == 2
            bytes_read = PB.decode(d, UInt64)
        elseif field_number == 3
            bytes_written = PB.decode(d, UInt64)
        elseif field_number == 4
            bytes_read_rate = PB.decode(d, Float32)
        elseif field_number == 5
            bytes_written_rate = PB.decode(d, Float32)
        elseif field_number == 6
            rpcs_executed = PB.decode(d, UInt64)
        elseif field_number == 7
            rpc_rate = PB.decode(d, Float32)
        elseif field_number == 8
            one_rpc_per_update = PB.decode(d, Bool)
        elseif field_number == 9
            max_time_per_update = PB.decode(d, UInt32)
        elseif field_number == 10
            adaptive_rate_control = PB.decode(d, Bool)
        elseif field_number == 11
            blocking_recv = PB.decode(d, Bool)
        elseif field_number == 12
            recv_timeout = PB.decode(d, UInt32)
        elseif field_number == 13
            time_per_rpc_update = PB.decode(d, Float32)
        elseif field_number == 14
            poll_time_per_rpc_update = PB.decode(d, Float32)
        elseif field_number == 15
            exec_time_per_rpc_update = PB.decode(d, Float32)
        elseif field_number == 16
            stream_rpcs = PB.decode(d, UInt32)
        elseif field_number == 17
            stream_rpcs_executed = PB.decode(d, UInt64)
        elseif field_number == 18
            stream_rpc_rate = PB.decode(d, Float32)
        elseif field_number == 19
            time_per_stream_update = PB.decode(d, Float32)
        else
            Base.skip(d, wire_type)
        end
    end
    return Status(
        version,
        bytes_read,
        bytes_written,
        bytes_read_rate,
        bytes_written_rate,
        rpcs_executed,
        rpc_rate,
        one_rpc_per_update,
        max_time_per_update,
        adaptive_rate_control,
        blocking_recv,
        recv_timeout,
        time_per_rpc_update,
        poll_time_per_rpc_update,
        exec_time_per_rpc_update,
        stream_rpcs,
        stream_rpcs_executed,
        stream_rpc_rate,
        time_per_stream_update,
    )
end

struct List
    items::Vector{Vector{UInt8}}
end
PB.default_values(::Type{List}) = (; items=Vector{Vector{UInt8}}())
PB.field_numbers(::Type{List}) = (; items=1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:List})
    items = PB.BufferedVector{Vector{UInt8}}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, items)
        else
            Base.skip(d, wire_type)
        end
    end
    return List(items[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::List)
    initpos = position(e.io)
    !isempty(x.items) && PB.encode(e, 1, x.items)
    return position(e.io) - initpos
end
function PB._encoded_size(x::List)
    encoded_size = 0
    !isempty(x.items) && (encoded_size += PB._encoded_size(x.items, 1))
    return encoded_size
end

struct Argument
    position::UInt32
    value::Vector{UInt8}
end
PB.default_values(::Type{Argument}) = (; position=zero(UInt32), value=UInt8[])
PB.field_numbers(::Type{Argument}) = (; position=1, value=2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Argument})
    position = zero(UInt32)
    value = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            position = PB.decode(d, UInt32)
        elseif field_number == 2
            value = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return Argument(position, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Argument)
    initpos = position(e.io)
    x.position != zero(UInt32) && PB.encode(e, 1, x.position)
    !isempty(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Argument)
    encoded_size = 0
    x.position != zero(UInt32) && (encoded_size += PB._encoded_size(x.position, 1))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct KRPCSet
    items::Vector{Vector{UInt8}}
end
PB.default_values(::Type{KRPCSet}) = (; items=Vector{Vector{UInt8}}())
PB.field_numbers(::Type{KRPCSet}) = (; items=1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:KRPCSet})
    items = PB.BufferedVector{Vector{UInt8}}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, items)
        else
            Base.skip(d, wire_type)
        end
    end
    return KRPCSet(items[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::KRPCSet)
    initpos = position(e.io)
    !isempty(x.items) && PB.encode(e, 1, x.items)
    return position(e.io) - initpos
end
function PB._encoded_size(x::KRPCSet)
    encoded_size = 0
    !isempty(x.items) && (encoded_size += PB._encoded_size(x.items, 1))
    return encoded_size
end

struct Exception
    name::String
    documentation::String
end
PB.default_values(::Type{Exception}) = (; name="", documentation="")
PB.field_numbers(::Type{Exception}) = (; name=1, documentation=2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Exception})
    name = ""
    documentation = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            documentation = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return Exception(name, documentation)
end

struct DictionaryEntry
    key::Vector{UInt8}
    value::Vector{UInt8}
end
PB.default_values(::Type{DictionaryEntry}) = (; key=UInt8[], value=UInt8[])
PB.field_numbers(::Type{DictionaryEntry}) = (; key=1, value=2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DictionaryEntry})
    key = UInt8[]
    value = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            key = PB.decode(d, Vector{UInt8})
        elseif field_number == 2
            value = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return DictionaryEntry(key, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DictionaryEntry)
    initpos = position(e.io)
    !isempty(x.key) && PB.encode(e, 1, x.key)
    !isempty(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DictionaryEntry)
    encoded_size = 0
    !isempty(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct ProcedureResult
    error::Union{Nothing,Error}
    value::Vector{UInt8}
end
PB.default_values(::Type{ProcedureResult}) = (; error=nothing, value=UInt8[])
PB.field_numbers(::Type{ProcedureResult}) = (; error=1, value=2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ProcedureResult})
    error = Ref{Union{Nothing,Error}}(nothing)
    value = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, error)
        elseif field_number == 2
            value = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return ProcedureResult(error[], value)
end

struct ConnectionResponse
    status::Int32
    message::String
    client_identifier::Vector{UInt8}
end
function PB.default_values(::Type{ConnectionResponse})
    return (; status=0, message="", client_identifier=UInt8[])
end
PB.field_numbers(::Type{ConnectionResponse}) = (; status=1, message=2, client_identifier=3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ConnectionResponse})
    status = 0
    message = ""
    client_identifier = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            status = PB.decode(d, Int32)
        elseif field_number == 2
            message = PB.decode(d, String)
        elseif field_number == 3
            client_identifier = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return ConnectionResponse(status, message, client_identifier)
end

struct ConnectionRequest
    client_name::String
    client_identifier::Vector{UInt8}
end
function PB.default_values(::Type{ConnectionRequest})
    return (; client_name="", client_identifier=UInt8[])
end
function PB.field_numbers(::Type{ConnectionRequest})
    return (; ty=1, client_name=2, client_identifier=3)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ConnectionRequest)
    initpos = position(e.io)
    !isempty(x.client_name) && PB.encode(e, 2, x.client_name)
    !isempty(x.client_identifier) && PB.encode(e, 3, x.client_identifier)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ConnectionRequest)
    encoded_size = 0
    !isempty(x.client_name) && (encoded_size += PB._encoded_size(x.client_name, 2))
    !isempty(x.client_identifier) &&
        (encoded_size += PB._encoded_size(x.client_identifier, 3))
    return encoded_size
end

struct ProcedureCall
    service::String
    procedure::String
    service_id::UInt32
    procedure_id::UInt32
    arguments::Vector{Argument}
end
function PB.default_values(::Type{ProcedureCall})
    return (;
        service="",
        procedure="",
        service_id=zero(UInt32),
        procedure_id=zero(UInt32),
        arguments=Vector{Argument}(),
    )
end
function PB.field_numbers(::Type{ProcedureCall})
    return (; service=1, procedure=2, service_id=4, procedure_id=5, arguments=3)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ProcedureCall)
    initpos = position(e.io)
    !isempty(x.service) && PB.encode(e, 1, x.service)
    !isempty(x.procedure) && PB.encode(e, 2, x.procedure)
    x.service_id != zero(UInt32) && PB.encode(e, 4, x.service_id)
    x.procedure_id != zero(UInt32) && PB.encode(e, 5, x.procedure_id)
    !isempty(x.arguments) && PB.encode(e, 3, x.arguments)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ProcedureCall)
    encoded_size = 0
    !isempty(x.service) && (encoded_size += PB._encoded_size(x.service, 1))
    !isempty(x.procedure) && (encoded_size += PB._encoded_size(x.procedure, 2))
    x.service_id != zero(UInt32) && (encoded_size += PB._encoded_size(x.service_id, 4))
    x.procedure_id != zero(UInt32) && (encoded_size += PB._encoded_size(x.procedure_id, 5))
    !isempty(x.arguments) && (encoded_size += PB._encoded_size(x.arguments, 3))
    return encoded_size
end

struct Dictionary
    entries::Vector{DictionaryEntry}
end
PB.default_values(::Type{Dictionary}) = (; entries=Vector{DictionaryEntry}())
PB.field_numbers(::Type{Dictionary}) = (; entries=1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Dictionary})
    entries = PB.BufferedVector{DictionaryEntry}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, entries)
        else
            Base.skip(d, wire_type)
        end
    end
    return Dictionary(entries[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Dictionary)
    initpos = position(e.io)
    !isempty(x.entries) && PB.encode(e, 1, x.entries)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Dictionary)
    encoded_size = 0
    !isempty(x.entries) && (encoded_size += PB._encoded_size(x.entries, 1))
    return encoded_size
end

struct Response
    error::Union{Nothing,Error}
    results::Vector{ProcedureResult}
end
PB.default_values(::Type{Response}) = (; error=nothing, results=Vector{ProcedureResult}())
PB.field_numbers(::Type{Response}) = (; error=1, results=2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Response})
    error = Ref{Union{Nothing,Error}}(nothing)
    results = PB.BufferedVector{ProcedureResult}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, error)
        elseif field_number == 2
            PB.decode!(d, results)
        else
            Base.skip(d, wire_type)
        end
    end
    return Response(error[], results[])
end

struct Request
    calls::Vector{ProcedureCall}
end
PB.default_values(::Type{Request}) = (; calls=Vector{ProcedureCall}())
PB.field_numbers(::Type{Request}) = (; calls=1)

function PB.encode(e::PB.AbstractProtoEncoder, x::Request)
    initpos = position(e.io)
    !isempty(x.calls) && PB.encode(e, 1, x.calls)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Request)
    encoded_size = 0
    !isempty(x.calls) && (encoded_size += PB._encoded_size(x.calls, 1))
    return encoded_size
end
